image: docker:19.03.8

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.8-dind

build_image:
  tags:
    - docker
  script:
    - docker build -t mcadmin -f image/Dockerfile .
    - docker tag mcadmin registry:5000/mcadmin
    - docker push registry:5000/mcadmin