image: docker:19.03.8

variables:
  DOCKER_DRIVER: overlay2
  MY_IMAGE: $MY_REGISTRY/mcadmin

services:
  - name: docker:19.03.8-dind
    command: ["--insecure-registry=192.168.1.49:5000"]

build_image:
  tags:
    - docker
  script:
    - echo $MY_IMAGE
    - echo $MY_REGISTRY
    - docker pull $MY_IMAGE
    - docker build --cache-from $MY_IMAGE -t mcadmin -t $MY_IMAGE -f image/Dockerfile .
    - docker push $MY_IMAGE

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack minecraft --service mcadmin --new-image $MY_IMAGE 