image: docker:19.03.8

variables:
  DOCKER_DRIVER: overlay2
  MY_IMAGE: $MY_REGISTRY/mcadmin
  MY_DHIMAGE: hcsama/mcadmin:1.0

services:
  - name: docker:19.03.8-dind
    command: ["--insecure-registry=192.168.1.49:5000"]

Build image:
  stage: build
  tags:
    - docker
  script:
    - docker pull $MY_IMAGE
    - docker build --cache-from $MY_IMAGE -t mcadmin -t $MY_IMAGE -f image/Dockerfile .
    - docker push $MY_IMAGE

Deploy to local registry:
  stage: test
  tags:
    - docker
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack minecraft --service mcadmin --new-image $MY_IMAGE

Deploy to docker hub:
  stage: deploy
  tags:
    - docker
  when: manual
  script:
    - docker login -u hcsama -p $DOCKERHUB_SECRET
    - docker pull $MY_IMAGE
    - docker tag $MY_IMAGE $MY_DHIMAGE
    - docker push $MY_DHIMAGE
